fieldLayouts:
  1380e5b2-3d69-4869-aebe-1a4dd9afbe17:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: da60d145-478b-42a4-801b-4e7c3e5076b7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9e0f6723-0abc-48db-8395-578391d4321c # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07d81829-f145-4483-b992-1f4e9ba2da8c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4ab0652-eb0d-4a94-8586-aa9e597f372c # Asset
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fef6a7ca-6907-4015-be78-66fa518eb075
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f992bd9a-db8d-4f05-836c-42c4c1b210ed # ExternalUrl
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cea6b8e8-2b06-4b6d-8063-371749ff68cf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 49a8c47e-571a-4f9c-ad29-4e16aabddb6d # Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de80d8ae-1339-4be0-adf6-aab7cc7d22cc
            userCondition: null
            warning: null
            width: 100
        name: Banners
        uid: 6c4e2b47-5856-49eb-aeba-d4e1c0265e86
        userCondition: null
handle: banners
hasTitleField: false
name: Banners
section: d3e69d4c-4721-478d-9ca2-b24c3a77b818 # Main
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
