fieldLayouts:
  f17727c3-b070-4be3-8c7f-ba5b7dd26e55:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e3169fde-4d5b-4a9b-bfe4-11ce613eabd4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f992bd9a-db8d-4f05-836c-42c4c1b210ed # ExternalUrl
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ff9918b-df40-48d1-b4a2-a7a0f9353439
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4ab0652-eb0d-4a94-8586-aa9e597f372c # Asset
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f701b43d-4dde-4daf-95cc-49165f2e705f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e726f341-e7cf-44d8-9015-718e660cecbf
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: e91a3058-1a3e-42d6-be7e-802ae6c71959 # Socials
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
