fieldLayouts:
  869cab44-041e-4118-b172-2c3c40610fe2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b990da1d-aef8-4e9d-bbdc-4da9986bf42d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2b885c57-3670-46a5-a62c-4d9b14448097 # Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cf13710-ac5b-467a-8eef-e3c2e4b2b66d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f44fae7f-f3e0-4625-a841-ebb232598950 # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 538243c3-ea95-434a-b7f6-3547e40618ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fdb1dfac-ad6f-4b89-9500-3a59d2820d69 # Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00650067-006c-4a89-b1e8-f50c5f119e14
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 099aaeb4-a8d4-4aa3-bd3a-8a41a7f4b7e8
        userCondition: null
handle: default
hasTitleField: true
name: Standaard
section: 2cc70982-ac78-4ae6-85c1-3a881fabc807 # Briefing Room Case
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
