fieldLayouts:
  a512b423-4312-4268-a3b1-e65852ca0873:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6f31039a-b51f-42f8-be46-0390838fa8ae
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f44fae7f-f3e0-4625-a841-ebb232598950 # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cbeda4d-1415-40a3-982b-6e420209cd05
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 592ff29e-2948-44e6-b497-82200ac5d4be
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: a014910c-11c7-4596-8d2b-1a481521db29 # Priority case
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
