fieldLayouts:
  0e40c23f-2ef8-4ada-9645-00214bbf5eb0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3baa430a-c6ee-4734-84be-3d8c76eac244
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 160dd163-d13d-451e-99da-c57782446044 # matrixField
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cdd45c9e-2291-4439-bf1b-3dff4c854b94
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6a908859-725a-4fa8-ae63-b3e53ab1937a
        userCondition: null
handle: matrix
hasTitleField: true
name: Matrix
section: d3e69d4c-4721-478d-9ca2-b24c3a77b818 # Main
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
