fieldLayouts:
  ce17482d-cccd-4df6-aeb8-163ff0a69534:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 58f6bad0-74a3-430a-b367-2d66b83f1294
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f44fae7f-f3e0-4625-a841-ebb232598950 # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26be988e-b0f2-4a6f-8127-542a01a08013
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 31fdd158-5015-463a-85e2-d4dfb5eef655
        userCondition: null
handle: privacypolicy
hasTitleField: true
name: privacyPolicy
section: 5049ce8a-20d3-4510-899a-d4e5ecd4263f # privacyPolicy
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
