fieldLayouts:
  84229a2a-d937-49e3-aa97-986281ce08f3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b31624da-bf89-44df-90ef-dc8ade8defda
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3f54db97-bc4c-4304-8eed-928d15131c50
        userCondition: null
fs: administration
handle: administration
name: Administration
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
