columnSuffix: null
contentColumnType: string
fieldGroup: 07382fe0-6e29-4dea-ba8f-647254e6bae5 # Common
handle: category
instructions: null
name: Category
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:4d8874c0-6b10-4038-92ba-e2078f2b1aee' # Category BriefingRoom
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
