columnSuffix: gicglfpk
contentColumnType: datetime
fieldGroup: 07382fe0-6e29-4dea-ba8f-647254e6bae5 # Common
handle: date
instructions: null
name: Date
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
