columnSuffix: mrntlfpl
contentColumnType: string(255)
fieldGroup: 07382fe0-6e29-4dea-ba8f-647254e6bae5 # Common
handle: externalurl
instructions: null
name: ExternalUrl
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: site
type: craft\fields\Url
