columnSuffix: ujijcxds
contentColumnType: text
fieldGroup: 07382fe0-6e29-4dea-ba8f-647254e6bae5 # Common
handle: tag
instructions: null
name: Tag
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
