defaultPlacement: end
enableVersioning: true
handle: administration
name: Administration
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a33dbeb7-7a84-494b-85f5-49871855c101: # La Casa Blanca
    enabledByDefault: true
    hasUrls: true
    template: pages/_administration.twig
    uriFormat: administration
  bf94dae5-2060-49f8-8495-3439a53edc7c: # The White House
    enabledByDefault: true
    hasUrls: true
    template: pages/_administration.twig
    uriFormat: administration
type: single
