defaultPlacement: end
enableVersioning: true
handle: briefingRoomCase
name: 'Briefing Room Case'
propagationMethod: all
siteSettings:
  a33dbeb7-7a84-494b-85f5-49871855c101: # La Casa Blanca
    enabledByDefault: true
    hasUrls: true
    template: pages/_detailBriefing.twig
    uriFormat: 'briefing-room/{slug}'
  bf94dae5-2060-49f8-8495-3439a53edc7c: # The White House
    enabledByDefault: true
    hasUrls: true
    template: pages/_detailBriefing.twig
    uriFormat: 'briefing-room/{slug}'
type: channel
